# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  INFRA_DIR: infra/
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: sa-east-1

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov mock
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  
    - name: Lint with flake8
      run: |
        flake8 --ignore=W504

    - name: Test with pytest
      run: |
        pytest --cov=. -vv --cov-fail-under=90 .
    
    - name: Terraform Plan
      run: |
        terraform -chdir=${{ env.INFRA_DIR }} init
        terraform -chdir=${{ env.INFRA_DIR }} validate
        terraform -chdir=${{ env.INFRA_DIR }} plan

    - name: Terraform Deploy
      run: terraform -chdir=${{ env.INFRA_DIR }} apply -auto-aprove
      