# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  INFRA_DIR: infra/

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov mock
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  
    - name: Lint with flake8
      run: |
        flake8 --ignore=W504

    - name: Test with pytest
      run: |
        pytest --cov=. -vv --cov-fail-under=90 .
    
    - name: Terraform Plan
      run: |
        terraform init     -chdir=${{ env.INFRA_DIR }}
        terraform validate -chdir=${{ env.INFRA_DIR }}
        terraform plan     -chdir=${{ env.INFRA_DIR }}
      